### ISSUE TITLE
Listar não funcionou

### ISSUE THREAD

**Issue by orlandosaraivajr** [JoaoCaastro/Prova-PHP#1]
Listar não funcionou com uso do firefox em ambiente Linux.
No diretório, alterei o privilégio para 777

**Comment by orlandosaraivajr** [comment]
[Tue Apr 05 19:24:21.579771 2022] [php7:warn] [pid 1169] [client 127.0.0.1:34078] PHP Warning:  fopen(cadastra.txt): failed to open stream: Permission denied in /var/www/html/tmp/Prova-PHP/realiza_cadastro.php on line 11, referer: http://127.0.0.1/tmp/Prova-PHP/cadastro.php

**Comment by JoaoCaastro** [comment]
O problema foi realmente no arquivo "realiza_cadastro.php", dentro do ambiente UNIX é necessário dar permissão de execução de comandos dentro dos arquivos:
$ chmod +x realiza_cadastro.php
